# This file has been generated by node2nix 1.8.0. Do not edit!

{ stdenvNoCC, pkgs ? import <nixpkgs> { inherit system; }
, system ? builtins.currentSystem, nodejs ? pkgs."nodejs-12_x"
, symlinkJoin ? pkgs.symlinkJoin, customConfigJsTarget ? null 
, version ? (import ./version.nix).version
, srcSha256 ? (import ./version.nix).srcSha256
}:

let
  nodeEnv = import ./node-env.nix {
    inherit (pkgs) stdenv python2 utillinux runCommand writeTextFile;
    inherit nodejs;
    libtool = if pkgs.stdenv.isDarwin then pkgs.darwin.cctools else null;
  };
  unconfigured-package = (import ./node-packages-unconfigured.nix {
    inherit (pkgs) fetchFromGitHub;
    inherit nodeEnv;
    inherit stdenvNoCC;
  }).package;
in
import ./wrapper.nix { 
  inherit symlinkJoin unconfigured-package customConfigJsTarget;
}