# This file has been generated by node2nix 1.8.0. Do not edit!

{ stdenvNoCC, nodeEnv, fetchFromGitHub, globalBuildInputs ? [ ]
, version ? (import ./version.nix).version
, srcSha256 ? (import ./version.nix).srcSha256 }:

let
  sources = { };
  args = {
    name = "turtl-js-unconfigured";
    packageName = "turtl-js";
    inherit version;
    src = fetchFromGitHub {
      owner = "turtl";
      repo = "js";
      rev = "v${version}";
      sha256 = srcSha256;
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Turtl's javascript interface";
      longDescription = ''
        turtl-js is the javascript core that runs the app whether on desktop or mobile.
        It contains Turtl's interfaces, logic, crypto, etc.
      '';
      license = stdenvNoCC.lib.licenses.gpl3;
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in {
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}
